# Files/directories to exclude from tree visualization
excluded_from_file_tree = [
  ".nuxt",
  ".git",
  ".output",
  "node_modules",
  ".project-context.toml",
  "build",
  "dist",
  "static-site-deployment-guide.md",
  "vuetify-3-for-Nuxt.md",
]

# Files/directories to completely ignore
ignored_paths = [
  ".nuxt",
  ".output",
  "yarn.lock",
  "node_modules",
  ".git",
  ".project-context.toml",
  "build",
  "dist",
  "static-site-deployment-guide.md",
  "vuetify-3-for-Nuxt.md",
]

# Paths to include in XML content
included_paths = [
  # ".DS_Store",
  # ".env",
  # "KASTOR_INTERNAL_DESCRIPTION.MD",
  # "LANDING_PAGE_STRUCTURE.md",
  # "README.md",
  # "app.vue",
  # "assets/css/global.css",
  # "components/BlogCard.vue",
  # "components/BlogList.vue",
  # "components/NavBar.vue",
  # "components/blog/breadcrumb.vue",
  # "components/landingpage/Benefits.vue",
  # "components/landingpage/CTASection.vue",
  # "components/landingpage/ContentTypes.vue",
  # "components/landingpage/DemoVideo.vue",
  # "components/landingpage/EarlyAccessModal.vue",
  # "components/landingpage/HowItWorks.vue",
  # "components/landingpage/ScrollCTA.vue",
  # "composables/useDataLayer.ts",
  # "content/blog/content-marketing/testPost2.md",
  # "content/blog/kastor/testPost.md",
  # "content/blog/tutorials/testPost.md",
  "layouts/default.vue",
  # "layouts/landingpage.vue",
  # "nuxt.config.ts",
  # "package.json",
  "pages/blog/[category]/[...slug].vue",
  # "pages/blog/[category]/index.vue",
  # "pages/blog/index.vue",
  # "pages/index.vue",
  "plugins/vuetify.ts",
  # "project-context.xml",
  # "public/.DS_Store",
  # "public/Kastor_square_dark_bg.svg",
  # "public/Kastor_square_light_bg.svg",
  # "public/Kastor_wordmark_dark_bg.svg",
  # "public/Kastor_wordmark_light_bg.svg",
  # "public/OG_image.png",
  # "public/campaign-creation.png",
  # "public/content-brief.png",
  # "public/content-type.png",
  # "public/favicon.ico",
  # "public/final-blog.png",
  # "public/kastor-demo-900.mp4",
  # "public/kastor-demo.mp4",
  # "public/robots.txt",
  # "public/tweet-creation.png",
  # "public/voice-creation.png",
  # "server/tsconfig.json",
  # "tsconfig.json",
  # "types/accessRequest.ts",
  # "types/global.d.ts"
]